### ISSUE TITLE
Class Site\ForumBundle\Model\Topic is not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by Leobaillard** [Herzult/HerzultForumBundle#42]
Hi,

I'm trying to install and configure the forum bundle with my existing site. I followed the documentation's instructions but I get an error when I try to display the forum index : **Class Site\ForumBundle\Model\Topic is not a valid entity or mapped super class**.

Here is my _config.yml_ :

``` yml
herzult_forum:
    db_driver:          orm
    class:
        model:
            category:   Site\ForumBundle\Model\Category
            topic:      Site\ForumBundle\Model\Topic
            post:       Site\ForumBundle\Model\Post
        blamer:
            topic:  Site\ForumBundle\Blamer\Blamer
            post:   Site\ForumBundle\Blamer\Blamer
```

_Topic.php_ entity :

```
<?php

namespace Site\ForumBundle\Model;

use Herzult\Bundle\ForumBundle\Entity\Topic as BaseTopic;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="Herzult\Bundle\ForumBundle\Entity\TopicRepository")
 */
class Topic extends BaseTopic
{
    /**
    * @ORM\ManyToOne(targetEntity="Category")
    */
    protected $category;

    /**
    * {@inheritDoc}
    */
    public function getAuthorName()
    {
        return 'Anonyme';
    }

    /**
    * @ORM\ReferenceOne(targetEntity="Site\UserBundle\Entity\User")
    */
    private $author;

    public function setAuthor( Site\UserBundle\Entity\User $user )
    {
        $this->author = $user;
    }

    public function getAuthor()
    {
        return $this->author;
    }
}
```

Any ideas ?
